### ISSUE TITLE
OPENMW alpha issues

### ISSUE THREAD

**Issue by Sisah2** [ptitSeb/gl4es#167] opened 2020-04-29 10:29 UTC
Some textures have bad alpha transparency, last commits dont solved this issue.
https://youtu.be/6AmqjvZzrDE

**Comment by Sisah2** [comment] 2020-04-29 10:42
Oh, my bad. Colors are correct. Only have alpha issues (rain, moons).

**Comment by Sisah2** [comment] 2020-04-29 18:31
Fixed  with dcb6f31

**Comment by Sisah2** [comment] 2020-05-02 15:42
just found some more black textures, and some black instead of alpha on modded trees, in combination with latest bug caused by 88e8203 i think better to reopen this.

**Comment by Sisah2** [comment] 2020-05-06 15:32
Also both issues (black textures, and white lines on mip maps) happening only on android, on linux pc with gl4es they are fine :(

**Comment by ptitSeb** [comment] 2020-05-06 17:19
Oh, that will make the debug more difficult.

I still have a few test to try, to check if I can reproduce some issues in some way.
If I cannot reproduce it, then I'll add some `#ifdef` around the mimpap handling of s3tc tetxures (as it seems this was what trigger this issue)

**Comment by ptitSeb** [comment] 2020-05-07 07:24
To check what is the cause of the issue, can you add, in `src/gl/texture_compressed.c` line 328, before the `gl4es_glTexSubImage2D(...)` this;
```
    if (level != 0) {
        noerrorShim();	
        return;	
    }
```
And see if the strippes / black texture are gone?

**Comment by Sisah2** [comment] 2020-05-07 08:20
Both are still here.

**Comment by ptitSeb** [comment] 2020-05-07 08:25
Mmm ok, strange.
Than can you comment, in the same file, lines 233-236 and lines 189-193

**Comment by Sisah2** [comment] 2020-05-07 08:59
It fixed stripes on mipmaps, but not black textures, it happening only on dxt5 textures that are not supposed to have alpha, like that one i uploaded, its just wall texture. i found some more of them in one normal mapped mod. no one of them work because they are saved with dxt5 compresion probably without alpha, because openmw normal maps need only rgb values, rgba is for parallax effect.

**Comment by ptitSeb** [comment] 2020-05-07 09:19
It doesn't make sense. I cannot understand why commenting the lines fixes the strippes. I don't understand why there are strippes here. And it's also more weird because all downsampling should be disabled on your side, so it should only do GL_RGBA/GL_UNSIGNED_BYTE, of GL_RGB for DXT1.

Also, DXT5 is an RGBA format, only DXT1 can be an RGB only format.

There seems to be something odd going on there. I also don't reproduce all those stripe/black texture issue on my Pandora, that have a mobile chipset.

Instead of comenting the lines, can you try to get the old and new value for format and type variables?

**Comment by Sisah2** [comment] 2020-05-07 09:30
You suggested comment out lines 233-236 then 189-193 88e8203 changed lines 154-158 then 189-193, so i think 189-183 is responsible for stripes.
Even blender cant open those dxt5 textures but gl4es 1.1.2 or commits before 3696d2b dont have problem with those textures.

**Comment by Sisah2** [comment] 2020-05-07 09:40
Blender says unexpected end of file when trying to open that texture. So i think some chck for that should be done, then fill alpha with zeroes. Not sure where to get old and new values, i must investigate little more.

**Comment by ptitSeb** [comment] 2020-05-07 09:44
To get values, you can change the block with
```
        if(level && bound->valid) {
            // don't mix type/format along mipmap...
            printf(" %s/%s =>", PrintEnum(format), PrintEnum(type);
            format = bound->format;
            type = bound->type;
            printf(" %s/%s\n", PrintEnum(format), PrintEnum(type);
        }
```

**Comment by Sisah2** [comment] 2020-05-07 10:18
so i think the only output of this is
05-07 12:16:57.919 21177 21439 I LIBGL   :  GL_RGBA/GL_UNSIGNED_BYTE =>
05-07 12:16:57.919 21177 21439 I LIBGL   :  GL_RGB/GL_UNSIGNED_BYTE

**Comment by ptitSeb** [comment] 2020-05-07 11:46
Ok.
I'll remove all mipmap handling for compressed texture first.

Then, we'll see for that black texture issue.

**Comment by Sisah2** [comment] 2020-05-07 12:32
It fixed stripes and black textures too. 
I also noticed one parallax texture which didnt worked properly with 1.1.2 it works fine now (its nicely smooth), but i also noticed one specular map which i thought was fine after 3696d2b and now look broken, not sure about that, i must try this one on pc.

**Comment by Sisah2** [comment] 2020-05-07 13:27
So that specular seems to be not gl4es related

**Comment by ptitSeb** [comment] 2020-05-08 09:26
I guess this ticket can be closed again.

**Comment by Sisah2** [comment] 2020-05-08 10:01
There is still one issue with alpha, some textures like mouse pointer, or some modded trees have black instead of alpha.

**Comment by ptitSeb** [comment] 2020-05-08 10:08
Are you sure this is related to DXTc texture?

**Comment by Sisah2** [comment] 2020-05-08 10:10
Not sure, i must find that texture first.

**Comment by ptitSeb** [comment] 2020-05-08 10:16
Especialy the mouse cursor, for me, the texture is created using a complicated mecanism with on offscreen buffer at launch. For me on gles2, it has no alpha because the pbuffer supported on GLES2 on my hardware if 565 only (which is a bit strange, but no other combinaison seems available)

**Comment by Sisah2** [comment] 2020-05-08 10:22
That cursor is broken only on pc for me, android use different pointer texture and its fine here. That tree texture was fine with 1.1.2 so i think recent changes with s3tc handling break it.

**Comment by ptitSeb** [comment] 2020-05-08 10:25
So cursor is probably something else (like the same hardware limitation I have on the Pandora).
The tree tetxure, what's it's format. Plus, it's mod, so it's difficult to test on my side.

**Comment by ptitSeb** [comment] 2020-05-08 11:23
Maybe my latest push fixed the issue on the non-transparent tree, because there was also an issue that could impact texture with alpha in custom shaders.

**Comment by Sisah2** [comment] 2020-05-08 11:25
Ok i try it, there is that texture. Just found it now :D
http://www.mediafire.com/file/6yclr9c24cx37sw/Tx_leaves_02.dds/file

**Comment by Sisah2** [comment] 2020-05-08 11:49
So that textere is still black, but shaders working nicely, even water reflection seems to work, awesome :)

**Comment by ptitSeb** [comment] 2020-05-08 12:24
That texture is a 512x512 DXT1 texture, with 10 mipmap. I'll check why the transparent info would not  be correctly set.

**Comment by ptitSeb** [comment] 2020-05-08 12:46
It should be fixed now. I tested with a small sample that show texture, and the leaf is trasparent now (it wasn't before).

**Comment by Sisah2** [comment] 2020-05-08 13:38
Good, no more black trees. Thank you. So i think it may be closed.

**Comment by ptitSeb** [comment] 2020-05-08 13:38
\o/

**Closed by ptitSeb** 2020-05-08 13:38 UTC
