### ISSUE TITLE
lwjgl crash

### ISSUE THREAD

**Issue by GFOXSH** [ptitSeb/gl4es#5] opened 2016-07-09 13:23 UTC
Log:

org.lwjgl.opengl.OpenGLException: Invalid enum (1280)
    at org.lwjgl.opengl.Util.checkGLError(Util.java:59)
    at org.lwjgl.opengl.DrawableGL.checkGLError(DrawableGL.java:82)
    at org.lwjgl.opengl.Display.swapBuffers(Display.java:605)
    at org.lwjgl.opengl.Display.update(Display.java:634)
    at org.lwjgl.opengl.Display.update(Display.java:616)
    at bao.g(SourceFile:869)
    at bbo.a(SourceFile:152)
    at bbo.c(SourceFile:73)
    at bao.a(SourceFile:1677)
    at bao.a(SourceFile:1652)
    at bjb.a(SourceFile:613)
    at hs.a(SourceFile:32)
    at hs.a(SourceFile:13)
    at ej.a(SourceFile:174)
    at bje.e(SourceFile:212)
    at bao.p(SourceFile:1306)
    at bao.ak(SourceFile:774)
    at bao.f(SourceFile:728)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at net.zhuoweizhang.boardwalk.MainActivity.runCraft2(MainActivity.java:636)
    at net.zhuoweizhang.boardwalk.MainActivity$3.onSurfaceCreated(MainActivity.java:213)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1494)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

If i enable NOERROR error probability decreases. But it does not disappear at all.

**Comment by ptitSeb** [comment] 2016-07-09 13:28
Mmm, I don't get it. With GL_NOERROR=1 you should never get a "Invalid enum" error. Can you copy/paste a log with GL_NOERROR=1 ?

**Comment by GFOXSH** [comment] 2016-07-09 13:30
@ptitSeb yes, of course. This log was created whit GL_NOERROR=1.

**Comment by GFOXSH** [comment] 2016-07-09 13:33
It turns out the same log ...

**Comment by ptitSeb** [comment] 2016-07-09 13:40
I just pushed a commit... Can you try it?

**Comment by GFOXSH** [comment] 2016-07-09 13:44
@ptitSeb yes, of course! But my friend, who build glshim in NDK is has no computer. Can you build static library for ARMv7?

**Comment by ptitSeb** [comment] 2016-07-09 13:46
Not riight now. I don't have access to any NDK / Android build machine... Maybe later.

**Comment by GFOXSH** [comment] 2016-07-09 15:21
It crash again...
[crash-2016-07-09_18.17.23-client.txt](https://github.com/ptitSeb/glshim/files/355603/crash-2016-07-09_18.17.23-client.txt)

**Comment by ptitSeb** [comment] 2017-01-16 18:24
You can now disable glError in your software:

use that:
```
#define GL_NOERROR_HINT_GL4ES           0xA10A
glHint(GL_NOERROR_HINT_GL4ES, 1);
```

And it will be the same as export GL_NOERROR=1

**Comment by ptitSeb** [comment] 2017-01-17 13:04
Closing it now. Feel free to open a new one (or this one) if the issue is still there.

**Closed by ptitSeb** 2017-01-17 13:04 UTC
