### ISSUE TITLE
A few regressions still extant

### ISSUE THREAD

**Issue by MagaTailor** [ptitSeb/gl4es#10] opened 2016-11-01 14:32 UTC
Probably for a week now I've seen regressions:

- Astromenace has been either slightly broken (borked textures) or, like currently, plain unusable (black screen, previous contents of video memory showing up)
- torcs likewise in the texture department, but now fails to start with `freeglut (/usr/local/lib/torcs/torcs-bin): Unable to create OpenGL 1.0 context (flags 0, profile 0)`

Tried a few others too but couldn't find any problems so the breakage looks rather specific.

**Comment by ptitSeb** [comment] 2016-11-01 15:11
Astromenace looks fine on my side, with latest glshim.

But I confirm torcs won't start. I'll look into that.

**Comment by ptitSeb** [comment] 2016-11-01 17:15
@petevine : should be fixed with c0184eaae45f7ba16c5a8e010add8fbd09c80259

**Comment by lubomyr** [comment] 2016-11-01 18:32
neverball 1.5.4 - problem with graphics after latest updates :(
also gfx regress with s25rttr & residualvm

**Comment by ptitSeb** [comment] 2016-11-01 18:45
Mmm, I just checked neverball before my last update. What regression did you have (can you put a screenshot).

Regression also with s24rttr (but this one never really worked) and residualvm too? Strange.

**Comment by ptitSeb** [comment] 2016-11-01 18:51
Look here is neverball on the Pandora. All effect are there and looks ok to me.
![neverball01](https://cloud.githubusercontent.com/assets/3250792/19902836/89959eb6-a06c-11e6-865e-db01a6ddd9e3.png)

**Comment by ptitSeb** [comment] 2016-11-01 19:00
But if c0184eaae45f7ba16c5a8e010add8fbd09c80259 broke them for you, then 659302519e7a7792dbd181c31aa770e97609a20b may help.

**Comment by lubomyr** [comment] 2016-11-01 19:41
![device-2016-11-01-213339](https://cloud.githubusercontent.com/assets/468950/19904407/15e6dad4-a07b-11e6-8733-1edaa3609ec3.png)

s25rttr - had problems with unreadable fonts and slow in-game speed. But now problem with textures.

**Comment by lubomyr** [comment] 2016-11-01 19:47
If i will have some free time i will try to investigate which commit (changes) caused this problems on android

**Comment by ptitSeb** [comment] 2016-11-01 20:12
@lubomyr ; are you using BATCH mode for neverball?

**Comment by lubomyr** [comment] 2016-11-01 20:14
no

**Comment by ptitSeb** [comment] 2016-11-01 20:14
Ok, strange, why the textures disapeared?!

**Comment by lubomyr** [comment] 2016-11-01 20:17
no idea, some app(s) as 'virtual jaguar' still works fine with glshim

**Comment by ptitSeb** [comment] 2016-11-01 20:20
any error in the log?

Maybe DEPTH or STENCIL are missing in the context creation ?

**Comment by ptitSeb** [comment] 2016-11-01 20:27
Mmm, no, not a depth or stencil issue, that picture just looks like all textures are gone! That's really odd.

**Comment by lubomyr** [comment] 2016-11-01 20:28
I take my words back. With virtual jaguar only black screen now.

**Comment by ptitSeb** [comment] 2016-11-01 20:29
Ok, so no texture everywhere. Strange, it's working fine here :S

**Comment by lubomyr** [comment] 2016-11-01 20:30
I do not see any errors in log

**Comment by ptitSeb** [comment] 2016-11-01 20:31
what are the extensions the glshim find?

**Comment by ptitSeb** [comment] 2016-11-01 20:33
maybe there is an issue with the NPOT texture ?

**Comment by lubomyr** [comment] 2016-11-01 20:38
How i can check extensions, these info not exist in android log ?

**Comment by ptitSeb** [comment] 2016-11-01 20:39
yes, in log.
Now glshim gives info about extension found, max textures, things like that.

**Comment by petevine** [comment] 2016-11-01 20:42
OK, torcs has been fixed, but Astromenace seemingly displays the contents of VRAM from a previous run. No problems with neverball here.

![astro](https://cloud.githubusercontent.com/assets/12054457/19906583/a1c4e384-a07b-11e6-8a62-6a80b541d413.jpg)

In the screenshot, foobillard stuff can be clearly recognised.

**Comment by ptitSeb** [comment] 2016-11-01 20:43
@petevine : any error in the log for you to in astromenace? Also, can you paste the extension glshim found ?

**Comment by lubomyr** [comment] 2016-11-01 20:44
i get log via new tag 'LIBGL' and old tag 'glshim'
In android.mk i still use old library name
 LOCAL_MODULE := glshim (not GL)
Can library name cause this problem ?

**Comment by ptitSeb** [comment] 2016-11-01 20:46
@lubomyr ; maybe. Also, note that I now use "-fvisibility=hidden" in the Makefile. Not sure this is enough to have everything but the textures.

**Comment by petevine** [comment] 2016-11-01 20:47
@ptitseb https://gist.github.com/petevine/20e219661c79719dc04ec7be51fa67f6

**Comment by lubomyr** [comment] 2016-11-01 20:48
I also uses -fvisibility=hidden
All the same except library name
I will try to rename it too

**Comment by petevine** [comment] 2016-11-01 20:50
@ptitSeb I'm not sure if the commit hash is stored in the compiled library so my last working version is dated `Oct 24 22:58`

**Comment by ptitSeb** [comment] 2016-11-01 20:53
@petevine : I think the issue is GL_OES_depth_texture that is detected and doesn't seems to work.

I will disable this for now, I need to debug that on my Odroid, but it will take time.

**Comment by ptitSeb** [comment] 2016-11-01 20:57
@petevine: this d76d6c916f26cf5469c5ce384d2f1ec144394b5d should fix Astromenace issue.

**Comment by petevine** [comment] 2016-11-01 21:01
@ptitSeb Indeed, thx! No more problems for now ;)

**Comment by ptitSeb** [comment] 2016-11-01 21:01
Good :D

**Comment by ptitSeb** [comment] 2016-11-01 21:14
@lubomyr : it is strange that you still get log using old "glshim" tag. it should be just LIBGL now. Maybe you are missing a few changes?

**Comment by lubomyr** [comment] 2016-11-01 21:27
I mean i monitored for tag glshim, but ofcourse with latest changes received all log with new tag LIBGL.
Also I use old library name because pelya's libSDL have a lot of different relation scripts which caused problem after rename lib.

**Comment by lubomyr** [comment] 2016-11-01 21:31
I always use symlink in my scripts :)
ln -sf libglshim.a $LOCAL_PATH/../../../obj/local/$1/libGL.a

**Comment by ptitSeb** [comment] 2016-11-01 21:37
ah ok. It's a static lib anyway, so name is not that important.

Still interested in the init log of glshim, things like:
LIBGL: built on Nov  1 2016 21:30:52
LIBGL: Extension GL_OES_point_sprite detected and used
LIBGL: Extension GL_OES_point_size_array detected

**Comment by lubomyr** [comment] 2016-11-01 21:44
I can see only
I/LIBGL   (10971): LIBGL: Initialising glshim
I/LIBGL   (10971): LIBGL:loaded: libGLESv1_CM.so
I/LIBGL   (10971): LIBGL:loaded: libEGL.so
nothing more :(

**Comment by ptitSeb** [comment] 2016-11-01 21:54
@lubomyr ; yes, I see some init stuff are missing.
Try this one a4766144a8ddc2356f2cc88fbeb9ed18e3287382

**Comment by ptitSeb** [comment] 2016-11-01 22:00
Actualy, this one 3f4bb05202364b605ae996e8e7273e7069deccb5 will build

**Comment by lubomyr** [comment] 2016-11-01 22:03
jni/../jni/glshim/src/gl/gl.c: In function 'initialize_glshim':
jni/../jni/glshim/src/gl/gl.c:222:1: error: expected ';' before '}' token

**Comment by ptitSeb** [comment] 2016-11-01 22:07
@lubomyr , yes, I forgot a ; it's fixed in next commit.

**Comment by lubomyr** [comment] 2016-11-01 22:14
big thanks for this fix

Neverball now works correct :)

I/LIBGL   (12813): LIBGL: Initialising glshim
I/LIBGL   (12813): LIBGL:loaded: libGLESv1_CM.so
I/LIBGL   (12813): LIBGL:loaded: libEGL.so
I/LIBGL   (12813): LIBGL: built on Nov  2 2016 00:02:12
I/LIBGL   (12813): LIBGL: Extension GL_OES_blend_subtract detected and used
I/LIBGL   (12813): LIBGL: Extension GL_OES_blend_func_separate detected and used
I/LIBGL   (12813): LIBGL: Extension GL_OES_blend_equation_separate detected and used
I/LIBGL   (12813): LIBGL: Extension GL_EXT_blend_minmax detected and used
I/LIBGL   (12813): LIBGL: Extension GL_OES_point_sprite detected and used
I/LIBGL   (12813): LIBGL: Extension GL_OES_point_size_array detected
I/LIBGL   (12813): LIBGL: Extension GL_OES_element_index_uint detected
I/LIBGL   (12813): LIBGL: Extension GL_OES_framebuffer_object detected and used
I/LIBGL   (12813): LIBGL: Extension GL_OES_packed_depth_stencil detected and used
I/LIBGL   (12813): LIBGL: Extension GL_OES_depth24 detected and used
I/LIBGL   (12813): LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
I/LIBGL   (12813): LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected
I/LIBGL   (12813): LIBGL: Max texture size: 8192
I/LIBGL   (12813): LIBGL: Texture Units: 8, Max lights: 8
I/LIBGL   (12813): LIBGL: Implementation Read is GL_RGBA/GL_UNSIGNED_BYTE
I/LIBGL   (12813): LIBGL: Current folder is:/

**Comment by lubomyr** [comment] 2016-11-01 22:15
other app(s) i will check later

**Comment by ptitSeb** [comment] 2016-11-01 22:17
Good !

**Comment by ptitSeb** [comment] 2016-11-01 22:17
I keep this ticket open in case there are other regressions

**Comment by lubomyr** [comment] 2016-11-01 22:26
I have excellent news:
no more slowdown with s25rttr.
game works with full speed.
only fonts still unreadable but it rather caused by FULL HD resolution in my device :)

**Comment by ptitSeb** [comment] 2016-11-01 22:28
Good :)

I'll check on s25rttr also myself latter.

**Comment by lubomyr** [comment] 2016-11-01 22:28
with older version of glshim, in-game speed was extreme slow, less than 0.1fps.

**Comment by MagaTailor** [comment] 2017-01-27 22:51
A current one in freeorion:
 
![evidence](https://cloud.githubusercontent.com/assets/12054457/22390437/511ecf44-e4eb-11e6-8322-983cc4a1534c.jpg)

**Comment by ptitSeb** [comment] 2017-01-28 08:19
I had introduced many regressions with the simple "DrawArrays / GL_QUADS" small optims. But I thought they were all fixed now. I'll check that.

**Comment by ptitSeb** [comment] 2017-01-28 08:56
Ok, I reproduce the bug on my side. I'll work on it.

**Comment by ptitSeb** [comment] 2017-01-28 10:35
Ok, fixed the freeorion issue with cb453c3753889c3d5c4b72764abc5ac0e258df53

**Comment by ptitSeb** [comment] 2017-01-29 13:16
I close this ticket. Fee free to open a new ticket if there is any new regression.

**Closed by ptitSeb** 2017-01-29 13:16 UTC
