### ISSUE TITLE
Fix powerGPU rendering error

### ISSUE THREAD

**Issue by magisk6666** [ptitSeb/gl4es#363] opened 2021-11-20 13:25 UTC
gl4es does not adapt well to powe vr GPU, there are many renderer problems in the game![Screenshot_2021-11-20-21-22-45-78_f9ee0578fe1cc94de7482bd41accb329.jpg](https://user-images.githubusercontent.com/77184424/142728009-785f16d1-4034-459f-8960-c7032311aabc.jpg)![Screenshot_2021-11-20-21-21-26-34_f9ee0578fe1cc94de7482bd41accb329.jpg](https://user-images.githubusercontent.com/77184424/142728012-f7c22170-8331-4858-bfb4-a59fc3dc386e.jpg)

**Comment by magisk6666** [comment] 2021-11-20 13:30
The source code of the game in the picture
[]()The source code of the game in the picture

**Comment by ptitSeb** [comment] 2021-11-20 13:47
Yes, I'm aware gl4es doesn't work well on the android source engine. There is some missing function like sRGB textures, that make it look not correct (texture way too bright or too dark).
It's not really about PowerVR GPU for now.

It's on my todo for at least a year. I need to work on this... one day...

**Comment by ptitSeb** [comment] 2022-03-16 15:40
duplicate of #348

**Closed by ptitSeb** 2022-03-16 15:40 UTC

**Comment by magisk666** [comment] 2022-03-19 14:09
> #348的副本[](https://github.com/ptitSeb/gl4es/issues/348)

However, the new source engine has been fixed and adapted to PVR.
